### ISSUE TITLE
Don’t export all the gogo_objects to .GlobalEnv

### ISSUE THREAD

**Issue by adam-gruer** [adam-gruer/inspectoRGadget#2]
In the purrr::walk call, each new object is assigned to .GlobalEnv . Is there a way of just adding these to the search path or another environment but still have the objects visible to Rstudio tab complete?

**Comment by hadley** [comment]
Create a new environment, assign the funs into it, and then attach() it to the search path.

**Comment by adam-gruer** [comment]
Awesome, thanks @hadley
